---
- hosts: db01
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: db01

- hosts: mc01
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: mc01

- hosts: rabbitmq01
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: rabbitmq01

- hosts: app01
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: app01