---
- name: Install RabbitMQ package
  yum:
    name: install centos-release-rabbitmq-38
    state: present

- name: Enable RabbitMQ service
  service:
    name:: rabbitmq-server
    enabled: yes
    state: started

- name: Start Firewalld
  service:
     name: firewalld
     state: started
     enabled: yes
     become: yes
  
- name: Enable Port 1234
  firewalld:
     zone: public
     port: 5672/tcp
     permanent: true
     state: enabled
     become: yes