---
- name: Creating directory 
  ansible.builtin.file:
    path: /home/ec2-user/
    state: directory
    mode: '0755'

- name: Install epel-release package
  yum:
    name: epel-release
    state: present

- name: Download esl-erlang package
  get_url:
    url: https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_23.3.1-1~centos~7_amd64.rpm
    dest: /home/ec2-user/esl-erlang_23.3.1-1~centos~7_amd64.rpm
    owner: root
    group: root
    mode: '0755'

- name: Download CompatOpenSSl
  get_url:
    url: https://pkgs.sysadmins.ws/el9/base/x86_64/compat-openssl10-1.0.2u-1.el9.x86_64.rpm
    dest: /home/ec2-user/compat-openssl10-1.0.2u-1.el9.x86_64.rpm
    owner: root
    group: root
    mode: '0755'

- name: Install openssl10
  yum:
    name: /home/ec2-user/compat-openssl10-1.0.2u-1.el9.x86_64.rpm
    state: present
  
- name: Install libncurses5
  yum:
    name: libncurses5
    state: present


- name: Install esl-erlang
  yum:
    name: /home/ec2-user/esl-erlang_23.3.1-1~centos~7_amd64.rpm
    state: present



# - name: Download erlang solutions
#   get_url:
#     url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
#     dest: /home/admin/erlang-solutions_1.0_all.deb
#     owner: admin
#     group: admin
#     mode: 0755

# - name: Install erlang repository
#   yum:
#     deb: /home/admin/erlang-solutions_1.0_all.deb

# - name: Add an Apt signing key
#   apt_key:
#     url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
#     state: present

# - name: fix unmet dependencies
#   shell: apt-get -f install

# - name: Add rabbit repo
#   shell: echo "deb https://dl.bintray.com/rabbitmq/debian stretch main" | tee /etc/apt/sources.list.d/bintray.rabbitmq.list

# - name: add trusted key
#   shell: wget -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc | apt-key add -

- name: install rabbitmq
  yum: 
    name: rabbitmq-server
    state: present
    update_cache: yes

- name: enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify:
    - restart rabbitmq

- name: add rabbitmq users admin
  rabbitmq_user:
    user: admin
    password: superpassword
    vhost: /
    tags: administrator
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Start Firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
    become: yes
  
- name: Enable Port 1234
  firewalld:
    zone: public
    port: 5672/tcp
    permanent: true
    state: enabled
    become: yes