---
- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install Maria-DB
  yum:
    name: mariadb-server
    state: present

- name: Start mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes
