---
- name: Install Memcached package
  yum:
    name: memcached
    state: present

- name: Ensure Memcached service is running and enabled
  service:
    name: memcached
    state: started
    enabled: yes
